/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.JOptionPane;

/**
 *
 * @author trezzi_luca
 */
public class Modifica extends javax.swing.JFrame {

    String user;
    String password;

    /**
     * Creates new form Modifica
     */
    public Modifica() {
        initComponents();
    }

    public Modifica(String User, String Password) {
        initComponents();
        user = User;
        password = Password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ModificaInfo = new javax.swing.JButton();
        ModificaPwd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ButtonGet = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NomeBlocco = new javax.swing.JTextField();
        RadioTemp = new javax.swing.JRadioButton();
        RadioPerm = new javax.swing.JRadioButton();
        TextData = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ButtonBlocca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Modifica");

        jLabel2.setText("Per modificare le informazioni");

        jLabel3.setText("Per modificare la password");

        ModificaInfo.setText("Modifica");
        ModificaInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaInfoActionPerformed(evt);
            }
        });

        ModificaPwd.setText("Modifica");
        ModificaPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaPwdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Per amministratore");

        ButtonGet.setText("Visualizza");
        ButtonGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGetActionPerformed(evt);
            }
        });

        jLabel5.setText("Visualizza elenco user");

        jLabel6.setText("Username");

        buttonGroup1.add(RadioTemp);
        RadioTemp.setText("Blocco temporaneo");

        buttonGroup1.add(RadioPerm);
        RadioPerm.setText("Blocco permanente");

        jLabel7.setText("fino a ");

        ButtonBlocca.setText("Blocca");
        ButtonBlocca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBloccaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioTemp)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextData, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RadioPerm))
                        .addContainerGap(76, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonBlocca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(NomeBlocco))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ModificaPwd)
                                    .addComponent(ModificaInfo)
                                    .addComponent(ButtonGet))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(50, 50, 50))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonBlocca, ButtonGet, ModificaInfo, ModificaPwd});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ModificaInfo))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ModificaPwd))
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonGet)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NomeBlocco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioTemp)
                    .addComponent(TextData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioPerm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonBlocca)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificaInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaInfoActionPerformed
        ModificaInfo modifica = new ModificaInfo(user, password);
        this.setVisible(false);
        modifica.setVisible(true);
    }//GEN-LAST:event_ModificaInfoActionPerformed

    private void ModificaPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaPwdActionPerformed
        ModificaPassword modificaPwd = new ModificaPassword(user, password);
        this.setVisible(false);
        modificaPwd.setVisible(true);
    }//GEN-LAST:event_ModificaPwdActionPerformed

    private void ButtonGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGetActionPerformed
        TCPClient TCP = new TCPClient();
        String Ricevuta = "";

        String invio = "GET_ALL," + user + "," + password;
        // con il tcp invio stringa

        try {
            TCP.GestioneSocketClient();
            TCP.inviaClient(invio);
            Ricevuta = TCP.riceviClient();
            TCP.chiudiClient();

            if (Ricevuta.equals("ERROR")) {
                JOptionPane.showMessageDialog(null, "NON SEI AMMINISTRATORE");
            } else {
                JOptionPane.showMessageDialog(null, Ricevuta);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "errore comunicazione");
        }
    }//GEN-LAST:event_ButtonGetActionPerformed

    private void ButtonBloccaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBloccaActionPerformed
        TCPClient TCP = new TCPClient();
        String userdabloccare = NomeBlocco.getText();
        String tempo = TextData.getText();
        String Ricevuta = "";
        String invio = "";
        
        if (RadioTemp.isSelected()) {
            invio = "BLOCCOTEMPORANEO," + userdabloccare + "," + tempo + "," + user + "," + password;
        } else if (RadioPerm.isSelected()) {
            invio = "BLOCCODEFINITIVO," + userdabloccare + "," + user + "," + password;
        }
        // con il tcp invio stringa

        try {
            TCP.GestioneSocketClient();
            TCP.inviaClient(invio);
            Ricevuta = TCP.riceviClient();
            TCP.chiudiClient();

            if (Ricevuta.equals("OK")) {
                Modifica modifica = new Modifica(user, password);
                this.setVisible(false);
                dispose();
                modifica.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "ERROR");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "errore comunicazione");
        }
    }//GEN-LAST:event_ButtonBloccaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBlocca;
    private javax.swing.JButton ButtonGet;
    private javax.swing.JButton ModificaInfo;
    private javax.swing.JButton ModificaPwd;
    private javax.swing.JTextField NomeBlocco;
    private javax.swing.JRadioButton RadioPerm;
    private javax.swing.JRadioButton RadioTemp;
    private javax.swing.JTextField TextData;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
